### ISSUE TITLE
Scratch 3.0 compatibility

### ISSUE THREAD

**Issue by wwj718** [ronilan/BlockLike#1]
BlockLike is a awesome educational project.

@ronilan  Are you planning to be compatible with [Scratch3.0](https://github.com/LLK/scratch-blocks)

**Comment by ronilan** [comment]
Short answer: BlockLike is compatible with Scratch 3.0.

Longer answer: It is as “compatible” with Scratch 3.0 just as it was “compatible” with Scratch 2.0.

Since BlockLike is not designed as a 1:1 textual clone of Scratch, but rather as a way to level-up from Scratch, some things are similar and are different.

There is more info in the FAQ as to what is similar, what is different and why: https://www.blocklike.org/faq.html
